import type { Article, TrendPoint, PipelineSummary, Newsletter } from '@/types';

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'Unilever acquires Minimalist skincare brand for $500M',
    summary: "Unilever has completed the acquisition of Indian skincare brand Minimalist for approximately $500 million, marking the company's largest beauty deal in Asia. The deal strengthens Unilever's position in the fast-growing Indian skincare market.",
    source: 'Reuters',
    published_date: '2026-03-15',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 28.0,
    score_deal: 22.5,
    score_recency: 10.0,
    deal_type_detected: 'Acquisition',
    relevance_score: 69.5,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '2',
    title: 'Nestlé leads $300M Series D in plant-based startup NotCo',
    summary: "Swiss food giant Nestlé leads a $300M Series D round in NotCo, the AI-powered plant-based protein company. The investment values NotCo at $2.5B and accelerates Nestlé's transition towards sustainable food offerings.",
    source: 'Bloomberg',
    published_date: '2026-03-14',
    url: '#',
    category: 'Investment',
    full_text: '',
    score_domain: 25.0,
    score_deal: 20.0,
    score_recency: 10.0,
    deal_type_detected: 'Investment',
    relevance_score: 64.0,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '3',
    title: 'KKR acquires majority stake in Haldiram\'s at $8.5B valuation',
    summary: "Private equity giant KKR is set to acquire a majority stake in Haldiram's snacks and sweets business at an $8.5 billion valuation, in one of the largest consumer goods deals in India this decade.",
    source: 'Economic Times',
    published_date: '2026-03-13',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 22.0,
    score_deal: 25.0,
    score_recency: 10.0,
    deal_type_detected: 'Stake Acquisition',
    relevance_score: 66.0,
    credibility_score: 7,
    source_tier: 2,
    credibility_flag: 'Tier 2 – verified outlet',
  },
  {
    id: '4',
    title: 'PepsiCo completes $1.2B acquisition of Siete Foods',
    summary: "PepsiCo has completed its $1.2 billion acquisition of Siete Foods, a rapidly growing Mexican-American food brand known for its grain-free tortillas and snacks. The deal was first announced in October 2023.",
    source: 'Bloomberg',
    published_date: '2026-03-12',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 26.0,
    score_deal: 22.5,
    score_recency: 10.0,
    deal_type_detected: 'Acquisition',
    relevance_score: 67.5,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '5',
    title: 'Reckitt divests infant nutrition business to Emmi for €2.7B',
    summary: "Reckitt Benckiser has agreed to sell its infant nutrition business, including the Mead Johnson brand, to Swiss dairy company Emmi AG for €2.7 billion. The divestiture is part of Reckitt's ongoing portfolio simplification strategy.",
    source: 'Financial Times',
    published_date: '2026-03-11',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 20.0,
    score_deal: 25.0,
    score_recency: 10.0,
    deal_type_detected: 'Divestiture',
    relevance_score: 64.0,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '6',
    title: 'Coca-Cola invests $200M in Ghost Energy drink brand',
    summary: "The Coca-Cola Company has made a significant $200 million minority investment in Ghost energy drinks, gaining distribution rights across North America. The investment reflects the surging demand for functional energy beverages.",
    source: 'CNBC',
    published_date: '2026-03-10',
    url: '#',
    category: 'Investment',
    full_text: '',
    score_domain: 24.0,
    score_deal: 20.0,
    score_recency: 5.0,
    deal_type_detected: 'Investment',
    relevance_score: 58.0,
    credibility_score: 7,
    source_tier: 2,
    credibility_flag: 'Tier 2 – verified outlet',
  },
  {
    id: '7',
    title: 'Diageo acquires Don Papa Rum for reported $400M',
    summary: "Spirits giant Diageo has acquired premium Philippine rum brand Don Papa for a reported $400 million, expanding its portfolio of super-premium spirits brands. The acquisition marks Diageo's first major Filipino spirits brand.",
    source: 'Reuters',
    published_date: '2026-03-09',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 22.0,
    score_deal: 22.5,
    score_recency: 5.0,
    deal_type_detected: 'Acquisition',
    relevance_score: 58.5,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '8',
    title: "L'Oréal acquires Aesop from Natura for $2.5B",
    summary: "L'Oréal has completed its acquisition of luxury skincare brand Aesop from Brazilian beauty group Natura & Co for $2.5 billion. The deal, one of the largest in beauty industry history, adds Aesop's 395 stores globally to L'Oréal's portfolio.",
    source: 'Bloomberg',
    published_date: '2026-03-08',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 26.0,
    score_deal: 22.5,
    score_recency: 5.0,
    deal_type_detected: 'Acquisition',
    relevance_score: 62.5,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '9',
    title: 'Kraft Heinz to divest Maxwell House coffee brand for $500M',
    summary: "Kraft Heinz announced plans to divest the Maxwell House coffee brand for approximately $500 million as part of its ongoing portfolio restructuring. The sale would allow the company to focus on higher-margin brands.",
    source: 'Wall Street Journal',
    published_date: '2026-03-07',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 22.0,
    score_deal: 25.0,
    score_recency: 5.0,
    deal_type_detected: 'Divestiture',
    relevance_score: 61.0,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '10',
    title: 'AB InBev forms joint venture with Budweiser APAC for $2B craft expansion',
    summary: "Anheuser-Busch InBev has announced a major joint venture with Budweiser APAC to invest $2 billion in craft beer brands across Asia Pacific over the next five years, betting on premiumisation in emerging markets.",
    source: 'Reuters',
    published_date: '2026-03-06',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 22.0,
    score_deal: 20.0,
    score_recency: 0.0,
    deal_type_detected: 'Joint Venture',
    relevance_score: 51.0,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '11',
    title: 'Mondelez acquires Clif Bar & Company for $2.9B',
    summary: "Mondelez International has completed its $2.9 billion acquisition of Clif Bar & Company, maker of the popular Clif energy bars. The deal adds one of the most recognized natural nutrition brands to Mondelez's snack portfolio.",
    source: 'Financial Times',
    published_date: '2026-03-05',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 24.0,
    score_deal: 22.5,
    score_recency: 0.0,
    deal_type_detected: 'Acquisition',
    relevance_score: 55.5,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '12',
    title: 'Danone sells Horizon Organic brand to private equity for $1.1B',
    summary: "French food multinational Danone has agreed to sell its Horizon Organic dairy brand to private equity firm Platinum Equity for $1.1 billion, part of the company's portfolio renewal strategy under CEO Antoine de Saint-Affrique.",
    source: 'Bloomberg',
    published_date: '2026-03-04',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 20.0,
    score_deal: 25.0,
    score_recency: 0.0,
    deal_type_detected: 'Divestiture',
    relevance_score: 54.0,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
];

export const MOCK_SUMMARY: PipelineSummary = {
  total_input: 38,
  after_dedup: 30,
  after_relevance: 25,
  final_count: 24,
  blocked: 1,
  dropped: 5,
  type_breakdown: {
    Acquisition: 12,
    Investment: 4,
    Divestiture: 4,
    'Stake Acquisition': 2,
    'Joint Venture': 1,
    Merger: 1,
  },
  domain_name: 'FMCG Deal Intelligence',
};

export const MOCK_TREND_DATA: TrendPoint[] = [
  { date: 'Jan 13', acquisitions: 3, investments: 1, divestitures: 1, total: 5 },
  { date: 'Jan 20', acquisitions: 2, investments: 2, divestitures: 0, total: 4 },
  { date: 'Jan 27', acquisitions: 4, investments: 1, divestitures: 2, total: 7 },
  { date: 'Feb 03', acquisitions: 3, investments: 3, divestitures: 1, total: 7 },
  { date: 'Feb 10', acquisitions: 5, investments: 2, divestitures: 1, total: 8 },
  { date: 'Feb 17', acquisitions: 4, investments: 1, divestitures: 3, total: 8 },
  { date: 'Feb 24', acquisitions: 6, investments: 3, divestitures: 2, total: 11 },
  { date: 'Mar 03', acquisitions: 5, investments: 2, divestitures: 2, total: 9 },
  { date: 'Mar 10', acquisitions: 7, investments: 4, divestitures: 1, total: 12 },
  { date: 'Mar 17', acquisitions: 8, investments: 3, divestitures: 3, total: 14 },
];

export const AI_QUICK_PROMPTS = [
  'Summarize today\'s top FMCG deals',
  'Which brand is most active in M&A?',
  'What sectors are attracting investment?',
  'Show divestiture trends this month',
  'Which deals are highest value?',
  'Compare acquisition vs investment activity',
];

// ── Mock Newsletter ───────────────────────────────────────────────────────────

export const MOCK_NEWSLETTER: Newsletter = {
  header: 'FMCG Deal Intelligence – Daily Brief',
  date: '2026-03-17',
  domain_name: 'FMCG Deal Intelligence',
  total_deals: 12,
  key_highlights: [
    {
      title: 'Unilever acquires Minimalist skincare brand for $500M',
      company: 'Unilever',
      deal_type: 'Acquisition',
      deal_value: '$500M',
      summary: "Unilever has completed the acquisition of Indian skincare brand Minimalist for approximately $500 million. The deal strengthens Unilever's position in the fast-growing Indian skincare market and marks its largest beauty deal in Asia.",
      source: 'Reuters',
      published_date: '2026-03-15',
      url: '#',
      relevance_score: 69.5,
      credibility_score: 9,
    },
    {
      title: 'Nestlé leads $300M Series D in plant-based startup NotCo',
      company: 'Nestlé',
      deal_type: 'Investment',
      deal_value: '$300M',
      summary: "Swiss food giant Nestlé leads a $300M Series D round in NotCo, the AI-powered plant-based protein company. The investment values NotCo at $2.5B and accelerates Nestlé's transition towards sustainable food offerings.",
      source: 'Bloomberg',
      published_date: '2026-03-14',
      url: '#',
      relevance_score: 64.0,
      credibility_score: 9,
    },
    {
      title: 'KKR acquires majority stake in Haldiram\'s Snacks at $8.5B valuation',
      company: 'KKR',
      deal_type: 'Stake Acquisition',
      deal_value: '$8.5B',
      summary: "Private equity giant KKR has acquired a majority stake in Haldiram's Snacks at a valuation of $8.5 billion. The deal is the largest private equity transaction in the Indian FMCG sector to date.",
      source: 'Financial Times',
      published_date: '2026-03-13',
      url: '#',
      relevance_score: 62.5,
      credibility_score: 9,
    },
  ],
  all_deals: [
    { company: 'Unilever', deal_type: 'Acquisition', summary: 'Acquires Minimalist skincare for $500M.', source: 'Reuters', published_date: '2026-03-15', deal_value: '$500M', relevance_score: 69.5, url: '#' },
    { company: 'Nestlé', deal_type: 'Investment', summary: 'Leads $300M Series D in NotCo.', source: 'Bloomberg', published_date: '2026-03-14', deal_value: '$300M', relevance_score: 64.0, url: '#' },
    { company: 'KKR', deal_type: 'Stake Acquisition', summary: 'Majority stake in Haldiram\'s at $8.5B valuation.', source: 'Financial Times', published_date: '2026-03-13', deal_value: '$8.5B', relevance_score: 62.5, url: '#' },
    { company: 'PepsiCo', deal_type: 'Acquisition', summary: 'Acquires Siete Foods for $1.2B.', source: 'CNBC', published_date: '2026-03-12', deal_value: '$1.2B', relevance_score: 60.0, url: '#' },
    { company: 'Reckitt', deal_type: 'Divestiture', summary: 'Divests homecare portfolio to PE firm for $800M.', source: 'Bloomberg', published_date: '2026-03-11', deal_value: '$800M', relevance_score: 57.0, url: '#' },
    { company: 'Coca-Cola', deal_type: 'Acquisition', summary: 'Acquires Ghost Energy brand in $990M deal.', source: 'WSJ', published_date: '2026-03-10', deal_value: '$990M', relevance_score: 55.5, url: '#' },
    { company: 'Diageo', deal_type: 'Acquisition', summary: 'Acquires Don Papa rum brand from Bleeding Heart Rum.', source: 'Reuters', published_date: '2026-03-09', deal_value: '', relevance_score: 52.0, url: '#' },
    { company: 'L\'Oréal', deal_type: 'Acquisition', summary: 'Completes full acquisition of Aesop for $2.5B.', source: 'Bloomberg', published_date: '2026-03-08', deal_value: '$2.5B', relevance_score: 51.0, url: '#' },
    { company: 'Kraft Heinz', deal_type: 'Divestiture', summary: 'Sells Planters nut brand as part of portfolio restructuring.', source: 'WSJ', published_date: '2026-03-07', deal_value: '', relevance_score: 49.5, url: '#' },
    { company: 'AB InBev', deal_type: 'Joint Venture', summary: 'Forms JV with Tilray for cannabis-infused beverages.', source: 'Bloomberg', published_date: '2026-03-06', deal_value: '', relevance_score: 47.0, url: '#' },
    { company: 'Mondelez', deal_type: 'Acquisition', summary: 'Acquires Clif Bar for $2.9B.', source: 'Reuters', published_date: '2026-03-05', deal_value: '$2.9B', relevance_score: 45.5, url: '#' },
    { company: 'Danone', deal_type: 'Divestiture', summary: 'Divests Horizon Organic brand to improve margins.', source: 'Financial Times', published_date: '2026-03-04', deal_value: '', relevance_score: 44.0, url: '#' },
  ],
  insights: [
    '📈 Acquisition activity is prominent, signalling market consolidation. (7 deals recorded this period)',
    '🔍 Beauty and personal care M&A is surging, led by premium D2C brands.',
    '🔍 Food & Beverage deals dominate — driven by shifting consumer preferences.',
    '⚡ High deal volume (12 records) suggests an active deal environment.',
    '💡 Rise in small-cap acquisitions and early-stage investments in new-age FMCG brands.',
  ],
  deal_type_breakdown: {
    Acquisition: 6,
    Investment: 2,
    Divestiture: 3,
    'Stake Acquisition': 1,
  },
  pipeline_summary: [
    { stage: '1 – Ingestion', input: 'Raw file', output: 38, notes: 'Loaded 38 records; normalised field names and dates.' },
    { stage: '2 – De-duplication', input: 38, output: 30, notes: 'Exact dedup via title hash + near-dedup via TF-IDF cosine (threshold=0.20). Removed 8 duplicates.' },
    { stage: '3 – Relevance Filtering', input: 30, output: 18, notes: 'Domain keyword score + deal keyword score (threshold=8.0). Filtered 12 off-topic records.' },
    { stage: '4 – Credibility Check', input: 18, output: 15, notes: '3-tier source whitelist. Hard-blocked 3 record(s) from unreliable sources.' },
    { stage: '5 – Summarization', input: 15, output: 15, notes: 'Extractive summarization: 2-line summaries per article. Extracted company names and deal values.' },
    { stage: '6 – Newsletter Generation', input: 15, output: '1 newsletter', notes: 'Structured newsletter: header + key highlights + all deals + insights.' },
    { stage: '7 – Output Formatting', input: 15, output: '15 records → 3 files', notes: 'Excel workbook (4 sheets) + JSON + CSV.' },
  ],
  text: '',
};
