import type { Article, TrendPoint, PipelineSummary } from '@/types';

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'Unilever acquires Minimalist skincare brand for $500M',
    summary: "Unilever has completed the acquisition of Indian skincare brand Minimalist for approximately $500 million, marking the company's largest beauty deal in Asia. The deal strengthens Unilever's position in the fast-growing Indian skincare market.",
    source: 'Reuters',
    published_date: '2026-03-15',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 28.0,
    score_deal: 22.5,
    score_recency: 10.0,
    deal_type_detected: 'Acquisition',
    relevance_score: 69.5,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '2',
    title: 'Nestlé leads $300M Series D in plant-based startup NotCo',
    summary: "Swiss food giant Nestlé leads a $300M Series D round in NotCo, the AI-powered plant-based protein company. The investment values NotCo at $2.5B and accelerates Nestlé's transition towards sustainable food offerings.",
    source: 'Bloomberg',
    published_date: '2026-03-14',
    url: '#',
    category: 'Investment',
    full_text: '',
    score_domain: 25.0,
    score_deal: 20.0,
    score_recency: 10.0,
    deal_type_detected: 'Investment',
    relevance_score: 64.0,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '3',
    title: 'KKR acquires majority stake in Haldiram\'s at $8.5B valuation',
    summary: "Private equity giant KKR is set to acquire a majority stake in Haldiram's snacks and sweets business at an $8.5 billion valuation, in one of the largest consumer goods deals in India this decade.",
    source: 'Economic Times',
    published_date: '2026-03-13',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 22.0,
    score_deal: 25.0,
    score_recency: 10.0,
    deal_type_detected: 'Stake Acquisition',
    relevance_score: 66.0,
    credibility_score: 7,
    source_tier: 2,
    credibility_flag: 'Tier 2 – verified outlet',
  },
  {
    id: '4',
    title: 'PepsiCo completes $1.2B acquisition of Siete Foods',
    summary: "PepsiCo has completed its $1.2 billion acquisition of Siete Foods, a rapidly growing Mexican-American food brand known for its grain-free tortillas and snacks. The deal was first announced in October 2023.",
    source: 'Bloomberg',
    published_date: '2026-03-12',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 26.0,
    score_deal: 22.5,
    score_recency: 10.0,
    deal_type_detected: 'Acquisition',
    relevance_score: 67.5,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '5',
    title: 'Reckitt divests infant nutrition business to Emmi for €2.7B',
    summary: "Reckitt Benckiser has agreed to sell its infant nutrition business, including the Mead Johnson brand, to Swiss dairy company Emmi AG for €2.7 billion. The divestiture is part of Reckitt's ongoing portfolio simplification strategy.",
    source: 'Financial Times',
    published_date: '2026-03-11',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 20.0,
    score_deal: 25.0,
    score_recency: 10.0,
    deal_type_detected: 'Divestiture',
    relevance_score: 64.0,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '6',
    title: 'Coca-Cola invests $200M in Ghost Energy drink brand',
    summary: "The Coca-Cola Company has made a significant $200 million minority investment in Ghost energy drinks, gaining distribution rights across North America. The investment reflects the surging demand for functional energy beverages.",
    source: 'CNBC',
    published_date: '2026-03-10',
    url: '#',
    category: 'Investment',
    full_text: '',
    score_domain: 24.0,
    score_deal: 20.0,
    score_recency: 5.0,
    deal_type_detected: 'Investment',
    relevance_score: 58.0,
    credibility_score: 7,
    source_tier: 2,
    credibility_flag: 'Tier 2 – verified outlet',
  },
  {
    id: '7',
    title: 'Diageo acquires Don Papa Rum for reported $400M',
    summary: "Spirits giant Diageo has acquired premium Philippine rum brand Don Papa for a reported $400 million, expanding its portfolio of super-premium spirits brands. The acquisition marks Diageo's first major Filipino spirits brand.",
    source: 'Reuters',
    published_date: '2026-03-09',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 22.0,
    score_deal: 22.5,
    score_recency: 5.0,
    deal_type_detected: 'Acquisition',
    relevance_score: 58.5,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '8',
    title: "L'Oréal acquires Aesop from Natura for $2.5B",
    summary: "L'Oréal has completed its acquisition of luxury skincare brand Aesop from Brazilian beauty group Natura & Co for $2.5 billion. The deal, one of the largest in beauty industry history, adds Aesop's 395 stores globally to L'Oréal's portfolio.",
    source: 'Bloomberg',
    published_date: '2026-03-08',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 26.0,
    score_deal: 22.5,
    score_recency: 5.0,
    deal_type_detected: 'Acquisition',
    relevance_score: 62.5,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '9',
    title: 'Kraft Heinz to divest Maxwell House coffee brand for $500M',
    summary: "Kraft Heinz announced plans to divest the Maxwell House coffee brand for approximately $500 million as part of its ongoing portfolio restructuring. The sale would allow the company to focus on higher-margin brands.",
    source: 'Wall Street Journal',
    published_date: '2026-03-07',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 22.0,
    score_deal: 25.0,
    score_recency: 5.0,
    deal_type_detected: 'Divestiture',
    relevance_score: 61.0,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '10',
    title: 'AB InBev forms joint venture with Budweiser APAC for $2B craft expansion',
    summary: "Anheuser-Busch InBev has announced a major joint venture with Budweiser APAC to invest $2 billion in craft beer brands across Asia Pacific over the next five years, betting on premiumisation in emerging markets.",
    source: 'Reuters',
    published_date: '2026-03-06',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 22.0,
    score_deal: 20.0,
    score_recency: 0.0,
    deal_type_detected: 'Joint Venture',
    relevance_score: 51.0,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '11',
    title: 'Mondelez acquires Clif Bar & Company for $2.9B',
    summary: "Mondelez International has completed its $2.9 billion acquisition of Clif Bar & Company, maker of the popular Clif energy bars. The deal adds one of the most recognized natural nutrition brands to Mondelez's snack portfolio.",
    source: 'Financial Times',
    published_date: '2026-03-05',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 24.0,
    score_deal: 22.5,
    score_recency: 0.0,
    deal_type_detected: 'Acquisition',
    relevance_score: 55.5,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
  {
    id: '12',
    title: 'Danone sells Horizon Organic brand to private equity for $1.1B',
    summary: "French food multinational Danone has agreed to sell its Horizon Organic dairy brand to private equity firm Platinum Equity for $1.1 billion, part of the company's portfolio renewal strategy under CEO Antoine de Saint-Affrique.",
    source: 'Bloomberg',
    published_date: '2026-03-04',
    url: '#',
    category: 'M&A',
    full_text: '',
    score_domain: 20.0,
    score_deal: 25.0,
    score_recency: 0.0,
    deal_type_detected: 'Divestiture',
    relevance_score: 54.0,
    credibility_score: 9,
    source_tier: 1,
    credibility_flag: 'Tier 1 – verified outlet',
  },
];

export const MOCK_SUMMARY: PipelineSummary = {
  total_input: 38,
  after_dedup: 30,
  after_relevance: 25,
  final_count: 24,
  blocked: 1,
  dropped: 5,
  type_breakdown: {
    Acquisition: 12,
    Investment: 4,
    Divestiture: 4,
    'Stake Acquisition': 2,
    'Joint Venture': 1,
    Merger: 1,
  },
  domain_name: 'FMCG Deal Intelligence',
};

export const MOCK_TREND_DATA: TrendPoint[] = [
  { date: 'Jan 13', acquisitions: 3, investments: 1, divestitures: 1, total: 5 },
  { date: 'Jan 20', acquisitions: 2, investments: 2, divestitures: 0, total: 4 },
  { date: 'Jan 27', acquisitions: 4, investments: 1, divestitures: 2, total: 7 },
  { date: 'Feb 03', acquisitions: 3, investments: 3, divestitures: 1, total: 7 },
  { date: 'Feb 10', acquisitions: 5, investments: 2, divestitures: 1, total: 8 },
  { date: 'Feb 17', acquisitions: 4, investments: 1, divestitures: 3, total: 8 },
  { date: 'Feb 24', acquisitions: 6, investments: 3, divestitures: 2, total: 11 },
  { date: 'Mar 03', acquisitions: 5, investments: 2, divestitures: 2, total: 9 },
  { date: 'Mar 10', acquisitions: 7, investments: 4, divestitures: 1, total: 12 },
  { date: 'Mar 17', acquisitions: 8, investments: 3, divestitures: 3, total: 14 },
];

export const AI_QUICK_PROMPTS = [
  'Summarize today\'s top FMCG deals',
  'Which brand is most active in M&A?',
  'What sectors are attracting investment?',
  'Show divestiture trends this month',
  'Which deals are highest value?',
  'Compare acquisition vs investment activity',
];
